/**
 * Synthetic post-deploy harness runner.
 *
 * Entry point: `runPostDeploy(input, clients?)`. Used in two ways:
 *
 *   1. Library mode — imported by `agents/editor/tools/post-deploy.ts`
 *      so the editor agent's `postDeploy.invoke` tool can call the
 *      runner with the deploy result handy. See that file for the
 *      orchestrator binding.
 *
 *   2. Standalone mode — invoked from the CLI (`bin/post-deploy.ts`)
 *      so GitHub Actions can run the harness without going through the
 *      agent. The CLI reads stack outputs from a JSON file or env vars
 *      and prints the runner's `PostDeployOutput` to stdout.
 *
 * The flow, per `design.md`'s Components and Interfaces:
 *
 *   1. If `deployFailureLogs` is supplied, short-circuit with outcome
 *      `deploy-failure` (the upstream deploy errored; the harness was
 *      invoked but should not run the synthetic flow).
 *   2. Resolve `ApiEndpointUrl` and `QueueUrl` from `stackOutputs`.
 *      Missing outputs cause an outcome of `fail` with a clear report.
 *   3. POST a synthetic message to `<ApiEndpointUrl>messages` with a
 *      session-tagged body so the message is identifiable.
 *   4. Poll the queue (and the EgressFn's CloudWatch logs as a
 *      secondary signal) until the synthetic message is observed or
 *      the timeout elapses.
 *   5. Read the queue's encryption attributes; assert KMS-managed
 *      encryption is enabled (matches the FanoutStack's
 *      `QueueEncryption.KMS` config, see `modules/fanout/lib/fanout-stack.ts`).
 *   6. Aggregate the assertions:
 *        - all assertions pass and the message landed     -> `pass`
 *        - assertions partially fail (encryption mismatch
 *          but message landed) or some other soft failure -> `partial`
 *        - the message never landed within the timeout    -> `fail`
 *
 * Why both queue-poll and CloudWatch-log read?
 * The FanoutStack subscribes the queue to the topic AND attaches the
 * EgressFn to the queue via `SqsEventSource`. Whichever one drains the
 * queue first wins: under typical load the EgressFn pulls messages off
 * very quickly, so a queue scan may miss the message even on success.
 * Reading the EgressFn's CloudWatch log group complements the queue
 * scan: if either the queue or the log shows the synthetic message,
 * the assertion succeeds. The harness reports which path observed the
 * message in its report.
 */

import {
  CloudWatchLogsClient,
  FilterLogEventsCommand,
} from "@aws-sdk/client-cloudwatch-logs";
import {
  SQSClient,
  GetQueueAttributesCommand,
  ReceiveMessageCommand,
  DeleteMessageCommand,
} from "@aws-sdk/client-sqs";

import type {
  PostDeployInput,
  PostDeployOutcome,
  PostDeployOutput,
} from "./types";

import {
  runGapClosureCheck,
  type StackOutputs,
} from "../gap-closure/index";
import type { GapClosureResult } from "../gap-closure/types";

// Re-export the public type contract so importers can pull everything
// from `@agent-harness/post-deploy` without reaching into `./types`.
export type { PostDeployInput, PostDeployOutcome, PostDeployOutput };

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * How long the harness polls for the synthetic message before declaring
 * `fail`. 30 seconds is generous for a fan-out from API Gateway through
 * SNS to a Lambda-attached SQS queue (the typical end-to-end latency on
 * the FanoutStack is sub-second, so 30 seconds covers cold starts and
 * SNS retries).
 */
export const DEFAULT_POLL_TIMEOUT_MS = 30_000;

/**
 * Interval between polling attempts. Two seconds keeps the API call
 * volume manageable (around 15 attempts within the timeout) while still
 * being responsive enough that a quick happy path returns in a few
 * seconds.
 */
export const DEFAULT_POLL_INTERVAL_MS = 2_000;

/**
 * The HTTP path appended to `ApiEndpointUrl` when posting the synthetic
 * message. The reference module's API Gateway exposes `POST /messages`
 * (see `modules/fanout/lib/fanout-stack.ts`); the path is hard-coded
 * here because the harness is paired with the reference module.
 *
 * `ApiEndpointUrl` from CDK includes a trailing slash (e.g.,
 * `https://abc.execute-api.us-east-1.amazonaws.com/prod/`); the runner's
 * URL builder normalises so neither value needing nor rejecting the
 * trailing slash matters.
 */
const SYNTHETIC_MESSAGE_PATH = "messages";

/**
 * The KMS encryption assertion the harness makes on the queue.
 *
 * The FanoutStack configures the main queue with `QueueEncryption.KMS`
 * and a customer-managed key. CloudFormation surfaces this through
 * `KmsMasterKeyId` on `GetQueueAttributes`; a non-empty value indicates
 * KMS encryption is on. The harness does NOT pin a specific key id
 * because the key id is generated by CDK and varies per deploy; the
 * presence of any value is sufficient evidence that encryption-at-rest
 * is configured.
 */
const REQUIRED_QUEUE_ENCRYPTION_ATTRIBUTE = "KmsMasterKeyId";

/**
 * Allow-listed log group prefixes for the EgressFn read.
 *
 * The reference module names the EgressFn's log group with the stack
 * name as the prefix (CDK default for `lambda.Function` constructs).
 * `FanoutPreview` is the stack name from `agent-harness.config.json`.
 *
 * If a forker renames the stack, this constant updates and the test
 * updates with it. A runtime-config-driven version would drift
 * silently.
 */
const EGRESS_LOG_GROUP_PREFIX = "/aws/lambda/FanoutPreview";

// ---------------------------------------------------------------------------
// Client injection
// ---------------------------------------------------------------------------

/**
 * Pair of AWS SDK clients the runner uses, plus a `fetch` injection
 * point for the HTTP request to API Gateway.
 *
 * The fetch shape is a minimal subset of the global `fetch`: the runner
 * only reads `ok`, `status`, and `text()` from the Response. Tests pass
 * a stub function; standalone mode uses the global `fetch` (Node 20+
 * provides one).
 */
export type SqsClientLike = Pick<SQSClient, "send">;
export type LogsClientLike = Pick<CloudWatchLogsClient, "send">;

export type FetchLike = (
  url: string,
  init?: { method?: string; headers?: Record<string, string>; body?: string },
) => Promise<{
  readonly ok: boolean;
  readonly status: number;
  text(): Promise<string>;
}>;

export interface PostDeployClients {
  readonly sqs: SqsClientLike;
  readonly logs: LogsClientLike;
  readonly fetch: FetchLike;
  /**
   * Sleep override. Defaults to `setTimeout`-based delay; tests inject
   * an immediate-resolve stub so the polling loop runs without real
   * wall-clock waits.
   */
  readonly sleep?: (ms: number) => Promise<void>;
  /** Override for `Date.now()`-equivalent. Tests inject a virtual clock. */
  readonly now?: () => number;
  /** Override for the per-poll timeout/interval. Tests shrink these. */
  readonly pollTimeoutMs?: number;
  readonly pollIntervalMs?: number;
}

/**
 * Lazily-constructed default clients.
 *
 * Instantiating SDK clients eagerly at module load time triggers
 * credential and region resolution, which would fail in unit tests
 * that aren't passing a stub. Lazy construction defers that until the
 * first standalone-mode call.
 */
let cachedDefaultClients: PostDeployClients | undefined;
function getDefaultClients(): PostDeployClients {
  if (cachedDefaultClients === undefined) {
    cachedDefaultClients = {
      sqs: new SQSClient({}),
      logs: new CloudWatchLogsClient({}),
      // Node 20 provides a global `fetch`. Cast through `unknown` so this
      // file does not depend on `lib.dom.d.ts`; the `FetchLike` shape is
      // structurally compatible with the global fetch.
      fetch: (globalThis as { fetch: FetchLike }).fetch.bind(globalThis),
    };
  }
  return cachedDefaultClients;
}

/** Default sleep implementation. Used when `clients.sleep` is not set. */
function defaultSleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Resolve a stack output by name, accepting either the bare key
 * (e.g., `ApiEndpointUrl`) or the CDK-qualified key
 * (e.g., `FanoutPreview.ApiEndpointUrl`).
 *
 * `agents/editor/tools/cdk.ts`'s `parseStackOutputs` produces keys in
 * the qualified form because the CDK deploy stdout prints them that
 * way. Standalone-mode callers (the GitHub Action) may dump bare keys
 * via `cdk deploy --outputs-file`. Accepting either form lets both
 * paths work without a translation layer.
 */
function resolveStackOutput(
  outputs: Record<string, string> | undefined,
  key: string,
): string | undefined {
  if (outputs === undefined) return undefined;
  // Direct hit on the bare key.
  const direct = outputs[key];
  if (typeof direct === "string" && direct.length > 0) return direct;
  // Search for any `<stack>.<key>` form whose suffix matches.
  for (const [k, v] of Object.entries(outputs)) {
    if (k.endsWith(`.${key}`) && typeof v === "string" && v.length > 0) {
      return v;
    }
  }
  return undefined;
}

/**
 * Build the synthetic message body. Carries the session id and a
 * timestamp so the queue scan and the log search can identify the
 * harness's own message.
 *
 * Returns the body string and the embedded marker so callers can
 * search for the marker without reconstructing the body.
 */
export function buildSyntheticMessage(sessionId: string, now: () => number): {
  body: string;
  marker: string;
} {
  const marker = `post-deploy-${sessionId}-${now()}`;
  const body = JSON.stringify({ message: marker });
  return { body, marker };
}

/**
 * Normalise an API endpoint URL and the message path into a single URL.
 *
 * CDK's `ApiEndpointUrl` typically ends with `/`; the path constant has
 * no leading slash. Concatenate so the result is well-formed regardless
 * of whether the endpoint trailed with a slash.
 */
function buildPostUrl(apiEndpointUrl: string): string {
  const trimmed = apiEndpointUrl.endsWith("/")
    ? apiEndpointUrl
    : `${apiEndpointUrl}/`;
  return `${trimmed}${SYNTHETIC_MESSAGE_PATH}`;
}

// ---------------------------------------------------------------------------
// runPostDeploy
// ---------------------------------------------------------------------------

/**
 * Run the synthetic post-deploy flow against a deployed preview.
 *
 * Returns one of the four outcomes from `design.md` Data Models:
 *   `pass` | `fail` | `partial` | `deploy-failure`.
 *
 * Never throws on a flow failure: every failure mode lands in the
 * `PostDeployOutput`'s `outcome` and `report` so the editor agent's
 * loop sees a structured signal regardless of what went wrong.
 *
 * Spawn-class errors (e.g., the SDK throws on a malformed client) do
 * propagate; those indicate a bug in the harness itself, not a
 * post-deploy assertion failure.
 */
export async function runPostDeploy(
  input: PostDeployInput,
  clientsOverride?: PostDeployClients,
): Promise<PostDeployOutput> {
  // 1. Short-circuit on upstream deploy failure.
  if (input.deployFailureLogs !== undefined) {
    return {
      outcome: "deploy-failure",
      report: {
        sessionId: input.sessionId,
        reason: "upstream cdk deploy errored; synthetic flow not run",
      },
      deployLogs: input.deployFailureLogs,
    };
  }

  const clients: PostDeployClients = clientsOverride ?? getDefaultClients();
  const sleep = clients.sleep ?? defaultSleep;
  const now = clients.now ?? Date.now;
  const pollTimeoutMs = clients.pollTimeoutMs ?? DEFAULT_POLL_TIMEOUT_MS;
  const pollIntervalMs = clients.pollIntervalMs ?? DEFAULT_POLL_INTERVAL_MS;

  // 2. Resolve the two stack outputs we need.
  const apiEndpointUrl = resolveStackOutput(input.stackOutputs, "ApiEndpointUrl");
  const queueUrl = resolveStackOutput(input.stackOutputs, "QueueUrl");
  if (apiEndpointUrl === undefined || queueUrl === undefined) {
    return {
      outcome: "fail",
      report: {
        sessionId: input.sessionId,
        reason:
          "missing required stack outputs (ApiEndpointUrl and QueueUrl must be present)",
        haveOutputs: input.stackOutputs ?? {},
      },
    };
  }

  // 3. Drive a synthetic message through API Gateway.
  const { body, marker } = buildSyntheticMessage(input.sessionId, now);
  const postUrl = buildPostUrl(apiEndpointUrl);
  let httpStatus: number;
  let httpResponseText: string;
  try {
    const response = await clients.fetch(postUrl, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body,
    });
    httpStatus = response.status;
    httpResponseText = await response.text();
    if (!response.ok) {
      return {
        outcome: "fail",
        report: {
          sessionId: input.sessionId,
          marker,
          reason: `synthetic POST returned non-2xx (${response.status})`,
          httpStatus,
          httpResponseText,
        },
      };
    }
  } catch (err) {
    return {
      outcome: "fail",
      report: {
        sessionId: input.sessionId,
        marker,
        reason: "synthetic POST threw before a response was received",
        error: err instanceof Error ? err.message : String(err),
      },
    };
  }

  // 4. Read the queue's encryption attributes once, up front. Doing this
  //    outside the polling loop means a one-time cost rather than a
  //    per-poll cost, and the result is the same regardless of when in
  //    the polling window the message lands.
  let queueEncryptionOk = false;
  let queueEncryptionDetail: string | undefined;
  let kmsMasterKeyId: string | undefined;
  try {
    const attrs = await clients.sqs.send(
      new GetQueueAttributesCommand({
        QueueUrl: queueUrl,
        AttributeNames: ["All"],
      }) as never,
    );
    const typed = attrs as {
      Attributes?: Record<string, string>;
    };
    kmsMasterKeyId = typed.Attributes?.[REQUIRED_QUEUE_ENCRYPTION_ATTRIBUTE];
    if (typeof kmsMasterKeyId === "string" && kmsMasterKeyId.length > 0) {
      queueEncryptionOk = true;
    } else {
      queueEncryptionDetail = `${REQUIRED_QUEUE_ENCRYPTION_ATTRIBUTE} attribute is absent or empty`;
    }
  } catch (err) {
    queueEncryptionDetail =
      err instanceof Error
        ? `GetQueueAttributes failed: ${err.message}`
        : `GetQueueAttributes failed: ${String(err)}`;
  }

  // 5. Poll until either the queue or the EgressFn log shows the marker,
  //    or the timeout elapses.
  const startedAt = now();
  const collectedLogs: Record<string, string> = {};
  let observedVia: "queue" | "logs" | undefined;
  let observedDetail: string | undefined;

  while (now() - startedAt < pollTimeoutMs) {
    // 5a. Try to receive a message off the queue. The EgressFn may have
    //     drained it first; if so we'll find the marker via logs.
    try {
      const recv = await clients.sqs.send(
        new ReceiveMessageCommand({
          QueueUrl: queueUrl,
          MaxNumberOfMessages: 10,
          WaitTimeSeconds: 0,
          // VisibilityTimeout 0 so we don't hold the message away from
          // the EgressFn while we read it. The DeleteMessage below
          // applies only to messages we matched.
          VisibilityTimeout: 0,
          AttributeNames: ["All"],
          MessageAttributeNames: ["All"],
        }) as never,
      );
      const typedRecv = recv as {
        Messages?: ReadonlyArray<{
          Body?: string;
          ReceiptHandle?: string;
          MessageId?: string;
        }>;
      };
      for (const msg of typedRecv.Messages ?? []) {
        if (typeof msg.Body === "string" && msg.Body.includes(marker)) {
          observedVia = "queue";
          observedDetail = `messageId=${msg.MessageId ?? "(unknown)"}`;
          // Clean up the synthetic message so it does not feed back to
          // the EgressFn (which would log a spurious entry on the next
          // run). Best-effort: ignore deletion errors.
          if (typeof msg.ReceiptHandle === "string") {
            await clients.sqs
              .send(
                new DeleteMessageCommand({
                  QueueUrl: queueUrl,
                  ReceiptHandle: msg.ReceiptHandle,
                }) as never,
              )
              .catch(() => {
                /* swallow: cleanup is best-effort */
              });
          }
          break;
        }
      }
    } catch {
      // Queue read errors are non-fatal: maybe the queue throttled or
      // there's a transient network issue. Fall through to the log
      // read; the next iteration of the polling loop will retry.
    }
    if (observedVia !== undefined) break;

    // 5b. Try the EgressFn log group. The handler logs each record's
    //     body, so the marker shows up in the log stream when the
    //     Lambda processed the synthetic message.
    try {
      const filter = await clients.logs.send(
        new FilterLogEventsCommand({
          logGroupName: `${EGRESS_LOG_GROUP_PREFIX}-EgressFn`,
          startTime: startedAt,
          filterPattern: `"${marker}"`,
          limit: 10,
        }) as never,
      );
      const typedFilter = filter as {
        events?: ReadonlyArray<{
          timestamp?: number;
          message?: string;
          logStreamName?: string;
        }>;
      };
      for (const event of typedFilter.events ?? []) {
        if (
          typeof event.message === "string" &&
          event.message.includes(marker)
        ) {
          observedVia = "logs";
          observedDetail = `logStream=${event.logStreamName ?? "(unknown)"}`;
          // Capture the matching log line so the agent's session
          // record sees the evidence.
          collectedLogs.egressFn = event.message;
          break;
        }
      }
    } catch {
      // Log read errors are non-fatal for the same reason as queue
      // read errors. The polling loop will try again.
    }
    if (observedVia !== undefined) break;

    await sleep(pollIntervalMs);
  }

  // 6. Aggregate.
  const messageObserved = observedVia !== undefined;
  const smokeAndFanoutOutcome: PostDeployOutcome = decideOutcome({
    messageObserved,
    queueEncryptionOk,
  });

  // 7. Gap-closure check (new, conditional on fitness-gap trigger).
  let gapClosureResult: GapClosureResult | null = null;
  if (input.triggerType === "fitness-gap" && input.originatingFinding) {
    const gcStackOutputs: StackOutputs = input.gapClosureStackOutputs ?? {};
    gapClosureResult = await runGapClosureCheck(
      input.originatingFinding,
      gcStackOutputs,
    );
  }

  // 8. Determine final outcome, factoring in gap-closure result.
  let outcome: PostDeployOutcome = smokeAndFanoutOutcome;
  if (gapClosureResult !== null) {
    if (gapClosureResult.probeError !== undefined) {
      // Probe error (transient AWS failure, missing stack output, unknown
      // finding ID) → partial: the harness could not fully verify closure.
      if (outcome === "pass" || outcome === "partial") {
        outcome = "partial";
      }
      // If smoke/fanout already failed, keep the harder "fail" outcome.
    } else if (!gapClosureResult.closed) {
      // Gap is confirmed not closed → fail.
      outcome = "fail";
    }
    // closed === true: gap-closure passed; do not override smoke/fanout outcome.
  }

  const report: Record<string, unknown> = {
    sessionId: input.sessionId,
    marker,
    apiEndpointUrl,
    queueUrl,
    httpStatus,
    httpResponseText,
    messageObserved,
    observedVia: observedVia ?? null,
    observedDetail: observedDetail ?? null,
    queueEncryption: {
      ok: queueEncryptionOk,
      kmsMasterKeyId: kmsMasterKeyId ?? null,
      detail: queueEncryptionDetail ?? null,
    },
    elapsedMs: now() - startedAt,
    gapClosure: gapClosureResult,
  };

  const output: PostDeployOutput =
    Object.keys(collectedLogs).length > 0
      ? { outcome, report, logs: collectedLogs }
      : { outcome, report };

  return output;
}

/**
 * Pure outcome aggregator. Lifted out of `runPostDeploy` so the test
 * suite can pin the truth table directly without going through the
 * polling machinery.
 *
 *   message  | encryption | outcome
 *   -------- | ---------- | --------
 *   yes      | yes        | pass
 *   yes      | no         | partial
 *   no       | yes        | fail
 *   no       | no         | fail
 *
 * Rationale: a missing message is the harder failure (the synthetic
 * flow did not complete); the encryption gap on top of a missing
 * message is still a `fail` because the dominant signal is that the
 * deploy is not delivering. An encryption gap with a successful
 * message is a `partial`: the deploy is wired up but a property the
 * design expects (KMS-encrypted SQS) is not observed.
 */
export function decideOutcome(args: {
  messageObserved: boolean;
  queueEncryptionOk: boolean;
}): PostDeployOutcome {
  if (!args.messageObserved) return "fail";
  if (!args.queueEncryptionOk) return "partial";
  return "pass";
}
